version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb_container
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: mydatabase
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  redis:
    image: redis:alpine
    container_name: redis_container
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: redis-server --requirepass redispassword123
    volumes:
      - redis_data:/data

volumes:
  mongodb_data:
  redis_data:

